id: 8c84ce7eee784c2e8735717ccaeb022a
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_130-The_Illusory_Absorption-v1
  language: bo
  author: ''
  volume: {}
